INSERT INTO department (name)
VALUES ('C-Suite'), 
       ('Accounting'), 
       ('Human Resources'), 
       ('Sales'), 
       ('IT'), 
       ('Customer Service'), 
       ('Marketing'), 
       ('Finance'), 
       ('Legal'), 
       ('Engineering'), 
       ('Operations'); 

INSERT INTO role (title, salary, department_id)
VALUES ('Chief Executive Officer', 250000, 1),
       ('Chief Human Resources Officer', 245000, 3),
       ('Chief Technology Officer', 245000, 5),
       ('Chief Financial Officer', 245000, 8),
       ('Chief Operations Officer', 245000, 11),
       ('Human Intranet Designer', 150000, 5),
       ('Senior Integration Engineer', 200000, 10),
       ('Corporate Solutions Representative', 125000, 6),
       ('Lead Usability Planner', 75000, 11),
       ('Senior Brand Planner', 85000, 7),
       ('Senior Bookkeeper', 150000, 2),
       ('Talent Acquisition Specialist', 60000, 3),
       ('Business systems analyst', 150000, 5),
       ('Compliance Officer', 120000, 9),
       ('Sales Associate', 55000, 4);

INSERT INTO employee (first_name, last_name, role_id, manager_id)
VALUES ('Max', 'Hayes', 1, NULL),
       ('Lance', 'Lane',4,1),
       ('Ben', 'Gould',12,6),
       ('Elijah', 'Warner',3,1),
       ('Chloe', 'Stewart',2,1),
       ('Isla', 'Cantrell',5,1),
       ('Ashtyn', 'Bridges',11,5),
       ('Heidi', 'Mendoza',13,4),
       ('Billy', 'Gibson',6,4),
       ('Branden', 'Olsen',7,4),
       ('Joseph', 'Moore',14,1),
       ('Ayden', 'Wallace',9,8),
       ('Jack', 'Simpson',10,1),
       ('Lucille', 'Kirby',15,1),
       ('Lexie', 'Wells',8,6);
